package cgeneration;

import java.util.*;
import tcpackage.*;

/* Just a wrapper class - generated by the SymbolTable class */
public class ClassesInfo{

	public Map<String, ObfuscatedClass> table_;

	public ClassesInfo(){
		table_ = new HashMap<String, ObfuscatedClass>();
	}


}